#!/usr/bin/env python3
"""
Genesis Tool: health_checker
Created: 2026-01-30T03:04:10.940203
Description: Utility für System-Gesundheits-Check

This tool was auto-generated by E-SIR Genesis Directive.
"""


def check_system_health():
    """Prüft CPU, RAM und Disk-Status."""
    import psutil
    cpu = psutil.cpu_percent()
    mem = psutil.virtual_memory().percent
    disk = psutil.disk_usage('/').percent
    return {
        "cpu_percent": cpu,
        "memory_percent": mem,
        "disk_percent": disk,
        "status": "healthy" if all([cpu < 80, mem < 85, disk < 90]) else "warning"
    }
