#!/usr/bin/env python3
"""
Genesis Tool: string_utils
Created: 2026-01-29T05:47:56.327556
Description: Basic string utility functions

This tool was auto-generated by E-SIR Genesis Directive.
"""


def reverse_string(s: str) -> str:
    """Reverse a string."""
    return s[::-1]

def count_vowels(s: str) -> int:
    """Count vowels in a string."""
    return sum(1 for c in s.lower() if c in "aeiou")
